database:
  GENCC_PATH: /Users/jenny/projects/Predisease/preview/db/gencc_submissions.tsv
  GENCC_NO_OMIM_PATH: /Users/jenny/projects/Predisease/preview/db/gencc.no_omim.tsv
  PANELAPP_UK_API_URL: https://panelapp.genomicsengland.co.uk/api/v1/genes/
  PANELAPP_UK_PATH: /Users/jenny/projects/Predisease/preview/db/panelapp.uk.genes_rawdata.tsv
  PANELAPP_AUS_API_URL: https://panelapp.agha.umccr.org/api/v1/genes/
  PANELAPP_AUS_PATH: /Users/jenny/projects/Predisease/preview/db/panelapp.aus.genes_rawdata.tsv
  MONDO_PATH: /Users/jenny/projects/Predisease/preview/db/mondo.obo
  MONDO_JSON_PATH: /Users/jenny/projects/Predisease/preview/db/mondo.json